---
- name: Converge
  hosts: all
  vars:
    sinteractive_homedir: '/opt/sinteractive'
    sinteractive_default_partition: 'fast'
  tasks:
    - name: "Include sinteractive"
      include_role:
        name: sinteractive
